AllCops:
  TargetRubyVersion: 2.0

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "mongoid-giza.gemspec"

Style/Encoding:
  Enabled: true
  EnforcedStyle: when_needed

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/StringLiterals:
  EnforcedStyle: double_quotes
